dist: trusty
sudo: false
language: php
php:
  - '5.6'
  - '7.1'
services:
  - mysql
before_install:
  - mysql -e 'DROP DATABASE IF EXISTS phproject; CREATE DATABASE phproject;'
install:
  - composer install
before_script:
  - if find . -name "*.php" ! -path "./vendor/*"  -exec php -l {} 2>&1 \; | grep "syntax error, unexpected"; then exit 1; fi
