dist: trusty
sudo: false
language: php
php:
  - '5.6'
  - '7.1'
before_script:
  - if find . -name "*.php" ! -path "./lib/*" -exec php -l {} 2>&1 \; | grep "syntax error, unexpected"; then exit 1; fi
